job:
  name: s2flow_lc_eval
  type: lc_eval
  log_dir: ./logs
  out_dir: ./runs
  load_checkpoint: False
  checkpoint_filename: checkpoint.pt
  cudnn_deterministic: False # set to False for faster training

lc_model:
  model_type: segformer
  in_channels: 4
  sample_size: 256
  num_classes: 7
  encoder_weights: imagenet
  pretrained_weights: ./runs/s2flow_lc_train/best_model.pt

data:
  samples_par_path: ./data/cpb_lc/samples.par
  data_dir_path: ./data/cpb_lc
  source_data: naip # options: s2, naip, s2sr
  fold: 1 # which cross-validation fold to use (1-5)
  augmentations: spatial
  num_workers: 8
  pin_memory: True
  
hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  micro_batch_size: 16 
  num_epochs: 1
  warmup_epochs: 10 
  weight_decay: 0.01
  use_amp: True