job:
  name: s2flow_lc_train_class_determination
  # type: lc_train
  type: lc_eval
  log_dir: ./logs
  out_dir: ./runs
  load_checkpoint: False
  checkpoint_filename: checkpoint.pt
  cudnn_deterministic: False # set to False for faster training

lc_model:
  model_type: segformer # options: unet, deeplabv3plus, segformer
  in_channels: 4
  sample_size: 256
  num_classes: 56
  encoder_weights: imagenet
  pretrained_weights: 'runs/s2flow_lc_train_class_determination/model.pt'

data:
  samples_par_path: ./data/cpb_lc/samples_fullscheme.par
  data_dir_path: ./data/cpb_lc
  source_data: s2sr # options: s2, naip, s2sr
  fold: 0 # which cross-validation fold to use (0-4)
  augmentations: spatial
  num_workers: 8
  pin_memory: True
  
hyperparameters:
  learning_rate: 0.0001
  batch_size: 32
  micro_batch_size: 16 
  num_epochs: 100
  warmup_epochs: 10 
  weight_decay: 0.01
  use_amp: True

eval:
  save_eval_samples: False