job:
  name: s2flow_lc_train
  type: lc_train
  log_dir: ./logs
  out_dir: ./runs
  load_checkpoint: True
  checkpoint_filename: checkpoint.pt
  cudnn_deterministic: False # set to False for faster training

lc_model:
  model_type: unet
  num_classes: 7

data:
  samples_par_path: ./data/cpb_lc/samples.par
  data_dir_path: ./data/cpb_lc
  source_data: s2 # options: s2, naip, s2sr
  fold: 1 # which cross-validation fold to use (1-5)
  augmentations: spatial
  num_workers: 8
  pin_memory: True
  
hyperparameters:
  learning_rate: 0.0001
  batch_size: 32
  micro_batch_size: 16 # set to 1024 for PCA computation
  num_epochs: 100
  warmup_epochs: 10 # just a test for now
  weight_decay: 0.01
  use_amp: True